// GENERATED by `npm run db:types` from the local database. Do not edit by hand.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  
  "graphql_public": {
          Tables: {
            [_ in never]: never
          }
          Views: {
            [_ in never]: never
          }
          Functions: {
            "graphql":
{ Args: { "extensions"?: Json,"operationName"?: string,"query"?: string,"variables"?: Json }; Returns: Json
                           }
          }
          Enums: {
            [_ in never]: never
          }
          CompositeTypes: {
            [_ in never]: never
          }
        },"public": {
          Tables: {
            "admins": {
                  Row: {
                    "created_at": string,"user_id": string
                  }
                  Insert: {
                    "created_at"?: string,"user_id": string
                  }
                  Update: {
                    "created_at"?: string,"user_id"?: string
                  }
                  Relationships: [
                    
                  ]
                },"articles": {
                  Row: {
                    "body": string | null,"cover_image_id": string | null,"created_at": string,"destination_id": string | null,"excerpt": string | null,"id": string,"is_visible": boolean,"kind": string,"published_on": string | null,"seo_description": string | null,"seo_title": string | null,"slug": string,"title": string,"updated_at": string
                  }
                  Insert: {
                    "body"?: string | null,"cover_image_id"?: string | null,"created_at"?: string,"destination_id"?: string | null,"excerpt"?: string | null,"id"?: string,"is_visible"?: boolean,"kind": string,"published_on"?: string | null,"seo_description"?: string | null,"seo_title"?: string | null,"slug": string,"title": string,"updated_at"?: string
                  }
                  Update: {
                    "body"?: string | null,"cover_image_id"?: string | null,"created_at"?: string,"destination_id"?: string | null,"excerpt"?: string | null,"id"?: string,"is_visible"?: boolean,"kind"?: string,"published_on"?: string | null,"seo_description"?: string | null,"seo_title"?: string | null,"slug"?: string,"title"?: string,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "articles_cover_image_id_fkey"
      columns: ["cover_image_id"]
isOneToOne: false
      referencedRelation: "media_assets"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "articles_destination_id_fkey"
      columns: ["destination_id"]
isOneToOne: false
      referencedRelation: "destinations"
      referencedColumns: ["id"]
    }
                  ]
                },"audit_logs": {
                  Row: {
                    "action": string,"actor_id": string | null,"at": string,"changes": Json | null,"id": number,"row_id": string | null,"table_name": string
                  }
                  Insert: {
                    "action": string,"actor_id"?: string | null,"at"?: string,"changes"?: Json | null,"id"?: never,"row_id"?: string | null,"table_name": string
                  }
                  Update: {
                    "action"?: string,"actor_id"?: string | null,"at"?: string,"changes"?: Json | null,"id"?: never,"row_id"?: string | null,"table_name"?: string
                  }
                  Relationships: [
                    
                  ]
                },"consultation_requests": {
                  Row: {
                    "client_country": string | null,"created_at": string,"email": string,"full_name": string,"handled_at": string | null,"handled_by": string | null,"id": string,"internal_note": string | null,"phone": string,"service_interest": string | null,"source_path": string | null,"status": string,"submission_id": string,"updated_at": string
                  }
                  Insert: {
                    "client_country"?: string | null,"created_at"?: string,"email": string,"full_name": string,"handled_at"?: string | null,"handled_by"?: string | null,"id"?: string,"internal_note"?: string | null,"phone": string,"service_interest"?: string | null,"source_path"?: string | null,"status"?: string,"submission_id": string,"updated_at"?: string
                  }
                  Update: {
                    "client_country"?: string | null,"created_at"?: string,"email"?: string,"full_name"?: string,"handled_at"?: string | null,"handled_by"?: string | null,"id"?: string,"internal_note"?: string | null,"phone"?: string,"service_interest"?: string | null,"source_path"?: string | null,"status"?: string,"submission_id"?: string,"updated_at"?: string
                  }
                  Relationships: [
                    
                  ]
                },"content_revisions": {
                  Row: {
                    "content_hash": string,"created_at": string,"created_by": string | null,"id": string,"note": string | null,"revision_number": number,"snapshot": NonNullable<Json>,"snapshot_schema_version": number
                  }
                  Insert: {
                    "content_hash": string,"created_at"?: string,"created_by"?: string | null,"id"?: string,"note"?: string | null,"revision_number"?: never,"snapshot": NonNullable<Json>,"snapshot_schema_version"?: number
                  }
                  Update: {
                    "content_hash"?: string,"created_at"?: string,"created_by"?: string | null,"id"?: string,"note"?: string | null,"revision_number"?: never,"snapshot"?: NonNullable<Json>,"snapshot_schema_version"?: number
                  }
                  Relationships: [
                    
                  ]
                },"destinations": {
                  Row: {
                    "created_at": string,"id": string,"image_id": string | null,"is_visible": boolean,"name": string,"slug": string,"sort_order": number,"summary": string | null,"updated_at": string
                  }
                  Insert: {
                    "created_at"?: string,"id"?: string,"image_id"?: string | null,"is_visible"?: boolean,"name": string,"slug": string,"sort_order"?: number,"summary"?: string | null,"updated_at"?: string
                  }
                  Update: {
                    "created_at"?: string,"id"?: string,"image_id"?: string | null,"is_visible"?: boolean,"name"?: string,"slug"?: string,"sort_order"?: number,"summary"?: string | null,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "destinations_image_id_fkey"
      columns: ["image_id"]
isOneToOne: false
      referencedRelation: "media_assets"
      referencedColumns: ["id"]
    }
                  ]
                },"doctor_services": {
                  Row: {
                    "doctor_id": string,"service_id": string
                  }
                  Insert: {
                    "doctor_id": string,"service_id": string
                  }
                  Update: {
                    "doctor_id"?: string,"service_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "doctor_services_doctor_id_fkey"
      columns: ["doctor_id"]
isOneToOne: false
      referencedRelation: "doctors"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "doctor_services_service_id_fkey"
      columns: ["service_id"]
isOneToOne: false
      referencedRelation: "services"
      referencedColumns: ["id"]
    }
                  ]
                },"doctors": {
                  Row: {
                    "bio": string | null,"created_at": string,"credentials": (string)[],"full_name": string,"id": string,"image_id": string | null,"is_visible": boolean,"languages": (string)[],"role_title": string | null,"slug": string,"sort_order": number,"updated_at": string
                  }
                  Insert: {
                    "bio"?: string | null,"created_at"?: string,"credentials"?: (string)[],"full_name": string,"id"?: string,"image_id"?: string | null,"is_visible"?: boolean,"languages"?: (string)[],"role_title"?: string | null,"slug": string,"sort_order"?: number,"updated_at"?: string
                  }
                  Update: {
                    "bio"?: string | null,"created_at"?: string,"credentials"?: (string)[],"full_name"?: string,"id"?: string,"image_id"?: string | null,"is_visible"?: boolean,"languages"?: (string)[],"role_title"?: string | null,"slug"?: string,"sort_order"?: number,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "doctors_image_id_fkey"
      columns: ["image_id"]
isOneToOne: false
      referencedRelation: "media_assets"
      referencedColumns: ["id"]
    }
                  ]
                },"faqs": {
                  Row: {
                    "answer": string | null,"created_at": string,"group_key": string,"id": string,"is_visible": boolean,"question": string,"sort_order": number,"updated_at": string
                  }
                  Insert: {
                    "answer"?: string | null,"created_at"?: string,"group_key": string,"id"?: string,"is_visible"?: boolean,"question": string,"sort_order"?: number,"updated_at"?: string
                  }
                  Update: {
                    "answer"?: string | null,"created_at"?: string,"group_key"?: string,"id"?: string,"is_visible"?: boolean,"question"?: string,"sort_order"?: number,"updated_at"?: string
                  }
                  Relationships: [
                    
                  ]
                },"locations": {
                  Row: {
                    "address_line": string | null,"created_at": string,"directions_url": string | null,"id": string,"image_id": string | null,"is_visible": boolean,"name": string,"slug": string,"sort_order": number,"updated_at": string
                  }
                  Insert: {
                    "address_line"?: string | null,"created_at"?: string,"directions_url"?: string | null,"id"?: string,"image_id"?: string | null,"is_visible"?: boolean,"name": string,"slug": string,"sort_order"?: number,"updated_at"?: string
                  }
                  Update: {
                    "address_line"?: string | null,"created_at"?: string,"directions_url"?: string | null,"id"?: string,"image_id"?: string | null,"is_visible"?: boolean,"name"?: string,"slug"?: string,"sort_order"?: number,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "locations_image_id_fkey"
      columns: ["image_id"]
isOneToOne: false
      referencedRelation: "media_assets"
      referencedColumns: ["id"]
    }
                  ]
                },"media_assets": {
                  Row: {
                    "alt_text": string | null,"created_at": string,"height": number | null,"id": string,"is_decorative": boolean,"kind": string,"mime_type": string,"poster_asset_id": string | null,"r2_key": string,"size_bytes": number,"status": string,"updated_at": string,"variant_widths": (number)[],"width": number | null
                  }
                  Insert: {
                    "alt_text"?: string | null,"created_at"?: string,"height"?: number | null,"id"?: string,"is_decorative"?: boolean,"kind": string,"mime_type": string,"poster_asset_id"?: string | null,"r2_key": string,"size_bytes": number,"status"?: string,"updated_at"?: string,"variant_widths"?: (number)[],"width"?: number | null
                  }
                  Update: {
                    "alt_text"?: string | null,"created_at"?: string,"height"?: number | null,"id"?: string,"is_decorative"?: boolean,"kind"?: string,"mime_type"?: string,"poster_asset_id"?: string | null,"r2_key"?: string,"size_bytes"?: number,"status"?: string,"updated_at"?: string,"variant_widths"?: (number)[],"width"?: number | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "media_assets_poster_asset_id_fkey"
      columns: ["poster_asset_id"]
isOneToOne: false
      referencedRelation: "media_assets"
      referencedColumns: ["id"]
    }
                  ]
                },"navigation_items": {
                  Row: {
                    "created_at": string,"href": string,"id": string,"is_visible": boolean,"label": string,"location": string,"sort_order": number,"updated_at": string
                  }
                  Insert: {
                    "created_at"?: string,"href": string,"id"?: string,"is_visible"?: boolean,"label": string,"location": string,"sort_order"?: number,"updated_at"?: string
                  }
                  Update: {
                    "created_at"?: string,"href"?: string,"id"?: string,"is_visible"?: boolean,"label"?: string,"location"?: string,"sort_order"?: number,"updated_at"?: string
                  }
                  Relationships: [
                    
                  ]
                },"package_items": {
                  Row: {
                    "created_at": string,"id": string,"label": string,"package_id": string,"sort_order": number,"updated_at": string
                  }
                  Insert: {
                    "created_at"?: string,"id"?: string,"label": string,"package_id": string,"sort_order"?: number,"updated_at"?: string
                  }
                  Update: {
                    "created_at"?: string,"id"?: string,"label"?: string,"package_id"?: string,"sort_order"?: number,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "package_items_package_id_fkey"
      columns: ["package_id"]
isOneToOne: false
      referencedRelation: "packages"
      referencedColumns: ["id"]
    }
                  ]
                },"packages": {
                  Row: {
                    "created_at": string,"currency": string | null,"description": string | null,"id": string,"image_id": string | null,"is_visible": boolean,"kind": string,"price_amount": number | null,"price_conditions": string | null,"service_id": string | null,"slug": string,"sort_order": number,"title": string,"updated_at": string
                  }
                  Insert: {
                    "created_at"?: string,"currency"?: string | null,"description"?: string | null,"id"?: string,"image_id"?: string | null,"is_visible"?: boolean,"kind": string,"price_amount"?: number | null,"price_conditions"?: string | null,"service_id"?: string | null,"slug": string,"sort_order"?: number,"title": string,"updated_at"?: string
                  }
                  Update: {
                    "created_at"?: string,"currency"?: string | null,"description"?: string | null,"id"?: string,"image_id"?: string | null,"is_visible"?: boolean,"kind"?: string,"price_amount"?: number | null,"price_conditions"?: string | null,"service_id"?: string | null,"slug"?: string,"sort_order"?: number,"title"?: string,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "packages_image_id_fkey"
      columns: ["image_id"]
isOneToOne: false
      referencedRelation: "media_assets"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "packages_service_id_fkey"
      columns: ["service_id"]
isOneToOne: false
      referencedRelation: "services"
      referencedColumns: ["id"]
    }
                  ]
                },"page_sections": {
                  Row: {
                    "created_at": string,"data": NonNullable<Json>,"data_version": number,"id": string,"is_visible": boolean,"page_id": string,"sort_order": number,"type": string,"updated_at": string
                  }
                  Insert: {
                    "created_at"?: string,"data"?: NonNullable<Json>,"data_version"?: number,"id"?: string,"is_visible"?: boolean,"page_id": string,"sort_order"?: number,"type": string,"updated_at"?: string
                  }
                  Update: {
                    "created_at"?: string,"data"?: NonNullable<Json>,"data_version"?: number,"id"?: string,"is_visible"?: boolean,"page_id"?: string,"sort_order"?: number,"type"?: string,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "page_sections_page_id_fkey"
      columns: ["page_id"]
isOneToOne: false
      referencedRelation: "pages"
      referencedColumns: ["id"]
    }
                  ]
                },"pages": {
                  Row: {
                    "created_at": string,"id": string,"is_enabled": boolean,"noindex": boolean,"og_image_id": string | null,"path": string,"seo_description": string | null,"seo_title": string | null,"title": string,"updated_at": string
                  }
                  Insert: {
                    "created_at"?: string,"id"?: string,"is_enabled"?: boolean,"noindex"?: boolean,"og_image_id"?: string | null,"path": string,"seo_description"?: string | null,"seo_title"?: string | null,"title": string,"updated_at"?: string
                  }
                  Update: {
                    "created_at"?: string,"id"?: string,"is_enabled"?: boolean,"noindex"?: boolean,"og_image_id"?: string | null,"path"?: string,"seo_description"?: string | null,"seo_title"?: string | null,"title"?: string,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "pages_og_image_id_fkey"
      columns: ["og_image_id"]
isOneToOne: false
      referencedRelation: "media_assets"
      referencedColumns: ["id"]
    }
                  ]
                },"publish_jobs": {
                  Row: {
                    "created_at": string,"deploy_ref": string | null,"error": string | null,"finished_at": string | null,"id": string,"queued_at": string,"requested_by": string | null,"revision_id": string,"started_at": string | null,"status": string,"updated_at": string
                  }
                  Insert: {
                    "created_at"?: string,"deploy_ref"?: string | null,"error"?: string | null,"finished_at"?: string | null,"id"?: string,"queued_at"?: string,"requested_by"?: string | null,"revision_id": string,"started_at"?: string | null,"status"?: string,"updated_at"?: string
                  }
                  Update: {
                    "created_at"?: string,"deploy_ref"?: string | null,"error"?: string | null,"finished_at"?: string | null,"id"?: string,"queued_at"?: string,"requested_by"?: string | null,"revision_id"?: string,"started_at"?: string | null,"status"?: string,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "publish_jobs_revision_id_fkey"
      columns: ["revision_id"]
isOneToOne: false
      referencedRelation: "content_revisions"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "publish_jobs_revision_id_fkey"
      columns: ["revision_id"]
isOneToOne: false
      referencedRelation: "live_revision"
      referencedColumns: ["id"]
    }
                  ]
                },"redirects": {
                  Row: {
                    "created_at": string,"from_path": string,"id": string,"status_code": number,"to_path": string,"updated_at": string
                  }
                  Insert: {
                    "created_at"?: string,"from_path": string,"id"?: string,"status_code"?: number,"to_path": string,"updated_at"?: string
                  }
                  Update: {
                    "created_at"?: string,"from_path"?: string,"id"?: string,"status_code"?: number,"to_path"?: string,"updated_at"?: string
                  }
                  Relationships: [
                    
                  ]
                },"services": {
                  Row: {
                    "created_at": string,"description": string | null,"id": string,"image_id": string | null,"is_visible": boolean,"price_text": string | null,"seo_description": string | null,"seo_title": string | null,"slug": string,"sort_order": number,"summary": string | null,"title": string,"updated_at": string
                  }
                  Insert: {
                    "created_at"?: string,"description"?: string | null,"id"?: string,"image_id"?: string | null,"is_visible"?: boolean,"price_text"?: string | null,"seo_description"?: string | null,"seo_title"?: string | null,"slug": string,"sort_order"?: number,"summary"?: string | null,"title": string,"updated_at"?: string
                  }
                  Update: {
                    "created_at"?: string,"description"?: string | null,"id"?: string,"image_id"?: string | null,"is_visible"?: boolean,"price_text"?: string | null,"seo_description"?: string | null,"seo_title"?: string | null,"slug"?: string,"sort_order"?: number,"summary"?: string | null,"title"?: string,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "services_image_id_fkey"
      columns: ["image_id"]
isOneToOne: false
      referencedRelation: "media_assets"
      referencedColumns: ["id"]
    }
                  ]
                },"site_settings": {
                  Row: {
                    "address_line": string | null,"contact_email": string | null,"copyright_text": string | null,"default_og_image_id": string | null,"id": boolean,"logo_asset_id": string | null,"logo_light_asset_id": string | null,"opening_hours": string | null,"phone_display": string | null,"phone_intl": string | null,"site_name": string,"social_links": NonNullable<Json>,"tagline": string | null,"updated_at": string,"whatsapp_url": string | null
                  }
                  Insert: {
                    "address_line"?: string | null,"contact_email"?: string | null,"copyright_text"?: string | null,"default_og_image_id"?: string | null,"id"?: boolean,"logo_asset_id"?: string | null,"logo_light_asset_id"?: string | null,"opening_hours"?: string | null,"phone_display"?: string | null,"phone_intl"?: string | null,"site_name": string,"social_links"?: NonNullable<Json>,"tagline"?: string | null,"updated_at"?: string,"whatsapp_url"?: string | null
                  }
                  Update: {
                    "address_line"?: string | null,"contact_email"?: string | null,"copyright_text"?: string | null,"default_og_image_id"?: string | null,"id"?: boolean,"logo_asset_id"?: string | null,"logo_light_asset_id"?: string | null,"opening_hours"?: string | null,"phone_display"?: string | null,"phone_intl"?: string | null,"site_name"?: string,"social_links"?: NonNullable<Json>,"tagline"?: string | null,"updated_at"?: string,"whatsapp_url"?: string | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "site_settings_default_og_image_id_fkey"
      columns: ["default_og_image_id"]
isOneToOne: false
      referencedRelation: "media_assets"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "site_settings_logo_asset_id_fkey"
      columns: ["logo_asset_id"]
isOneToOne: false
      referencedRelation: "media_assets"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "site_settings_logo_light_asset_id_fkey"
      columns: ["logo_light_asset_id"]
isOneToOne: false
      referencedRelation: "media_assets"
      referencedColumns: ["id"]
    }
                  ]
                }
          }
          Views: {
            "live_revision": {
                  Row: {
                    "content_hash": string | null,"created_at": string | null,"created_by": string | null,"id": string | null,"note": string | null,"revision_number": number | null,"snapshot": Json | null,"snapshot_schema_version": number | null
                  }
                  Relationships: [
                    
                  ]
                }
          }
          Functions: {
            "is_admin":
{ Args: Record<PropertyKey, never>; Returns: boolean
                           }
          }
          Enums: {
            [_ in never]: never
          }
          CompositeTypes: {
            [_ in never]: never
          }
        }
}

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
  ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
      Row: infer R
    }
    ? R
    : never
  : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
  ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
      Insert: infer I
    }
    ? I
    : never
  : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
  ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
      Update: infer U
    }
    ? U
    : never
  : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
  ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
  : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never
> = PublicCompositeTypeNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
  ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
  : never

export const Constants = {
  "graphql_public": {
          Enums: {
            
          }
        },"public": {
          Enums: {
            
          }
        }
} as const
